uploads = []
outputs = []

[[generated]]
id = "3vtVmB36V66ZQh_x6cTt9"
uri = "file://artifacts/galaxy-mobile/assets/images/icon.png"
type = "image"
title = "galaxy voice app icon"

[[generated]]
id = "22IMx1QdEGiv9sVdJIMIv"
uri = "file://artifacts/galaxy-mobile/assets/images/splash.png"
type = "image"
title = "galaxy voice splash screen"

[[generated]]
id = "ZTbTzhEA3fqGUAN7sVCIZ"
uri = "file://artifacts/galaxy-web/public/logo.png"
type = "image"
title = "generated_image"

[[generated]]
id = "0oXrmVCx-s1x5VLhoBBDR"
uri = "file://artifacts/galaxy-web/public/bg-mystical.png"
type = "image"
title = "generated_image"
